### ISSUE TITLE
Method 4 not working?

### ISSUE THREAD

**Issue by thepenguinthatwants** [angristan/arch-linux-install#7]
I tried the installation with ur guide and they work well but Method 4 - LVM on LUKS didnt seem t work.

Has something changed?

After the installation and the first startup I get

```
A start job is runnign for /dev/vg0/root -> then timeout
Dependency failed for initrd root device
Dependency failed for /sysroot
Dependency failed for initrd root file system
Dependency failed for Reload configuration from the real boot
Dependency failed for File system check on /dev/vg0/root
->
Emergency mode
```

Tried the installation multiple times yet always get the same results.

**Comment by exah-io** [comment]
@thepenguinthatwants i know it's  been a few months already, but did you ever find the issue? I'm facing it too.

Arch's wiki states the same steps though. It works fine with busybox, but not systemd.
